version: "2"
services: 
  migrations:
    environment:
      - NODE_ENV=test
      - PORT=5000
      - AWS_DEFAULT_REGION=ap-southeast-1
      - DB_URL=postgres://username:Dummy123@postgres/levantcarta-store
      - DB_URL_TEST=postgres://username:Dummy123@postgres/levantcarta-store
    command: yarn db:migrate

  
  levantcarta: 
    environment:
      - NODE_ENV=test
      - PORT=5000
      - AWS_DEFAULT_REGION=ap-southeast-1
      - DB_URL=postgres://username:Dummy123@postgres/levantcarta-store
      - DB_URL_TEST=postgres://username:Dummy123@postgres/levantcarta-store 
    command: yarn test
